version: '2'

networks:
  spark-intro-app-network:
    name: SparkIntroAppNetwork

services:
  spark-master:
    image: docker.io/bitnami/spark:3.5.1
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
      - '7077:7077'
    networks:
      - spark-intro-app-network
    volumes:
      - ./imdb-app/target/scala-2.12/spark-nytd-app-assembly-0.0.1.jar:/opt/apps/app.jar
      - ./app-vol:/var/tmp/data

  spark-worker:
    image: docker.io/bitnami/spark:3.5.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=5G
      - SPARK_WORKER_CORES=3
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    networks:
      - spark-intro-app-network
    ports:
      - '8081-8082:8081'
    volumes:
      - ./imdb-app/target/scala-2.12/spark-nytd-app-assembly-0.0.1.jar:/opt/apps/app.jar
      - ./app-vol:/var/tmp/data
    deploy:
      replicas: 2
